### ISSUE TITLE
Push to test pypi fails

### ISSUE THREAD

**Issue by chrisclark** [explorerhq/django-sql-explorer#630]
@marksweb I moved the owner of SQL Explorer to this organization (so it's no longer in my personal account). The test pypi pushes are now failing -- presumably because the repo under this new name is not set as a 'publisher'. I was able to fix this for pypi proper, but don't actually have the right permissions in test.pypi.org to manage the package, and therefore can't add the publisher myself. Could you please add me to the test pypi setup? Thanks!

**Comment by marksweb** [comment]
Done 👍

**Comment by chrisclark** [comment]
Thank you my friend!
