### ISSUE TITLE
Version 5.0 requires pandas ?

### ISSUE THREAD

**Issue by spapas** [explorerhq/django-sql-explorer#631]
I installed 5.0 and got:

```
  File "C:\progr\py3\ehcg\venv\lib\site-packages\explorer\ee\db_connections\utils.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

I don't wanna install pandas, can you please  make this dependency optional ?

**Comment by chrisclark** [comment]
Absolutely. An oversight. Will do a cut a 4.0.1 release tomorrow. If EXPLORER_USER_UPLOADS is not enabled, then there is no reason for the pandas dep. Will make it part of the uploads extra. Apologies.

**Comment by 2af** [comment]
pandas **is not** automatically installed with 
`pip install django-sql-explorer=5.0`

**Comment by chrisclark** [comment]
Yes exactly. Fixed here. https://github.com/explorerhq/django-sql-explorer/pull/632

Will cut a release shortly.
