### ISSUE TITLE
count is not coming correct in log in `truncate_querylogs`

### ISSUE THREAD

**Issue by fearless0307** [explorerhq/django-sql-explorer#636]
Hi,

in `explorer.tasks.snapshot_queries` func, inside logger, it's written as
```python
logger.info(
    f"Deleting {qs.count} QueryLog objects older than {days} days."
)
```
[Code link](https://github.com/explorerhq/django-sql-explorer/blob/64170743b46d310684982dfe745d65643c08e844/explorer/tasks.py#L102C5-L104C6)

Which results in log output as.
`Deleting <bound method QuerySet.count of <QuerySet [<QueryLog: QueryLog object (2585296)>, <QueryLog: QueryLog object (2585295)>, <QueryLog: QueryLog object (2585294)>, <QueryLog: QueryLog object (2585293)>, <QueryLog: QueryLog object (2585292)>, <QueryLog: QueryLog object (2585291)>, <QueryLog: QueryLog object (2585290)>, <QueryLog: QueryLog object (2585289)>, <QueryLog: QueryLog object (2585288)>, <QueryLog: QueryLog object (2585287)>, <QueryLog: QueryLog object (2585286)>, <QueryLog: QueryLog object (2585285)>, <QueryLog: QueryLog object (2585284)>, <QueryLog: QueryLog object (2585283)>, <QueryLog: QueryLog object (2585282)>, <QueryLog: QueryLog object (2585281)>, <QueryLog: QueryLog object (2585280)>, <QueryLog: QueryLog object (2585279)>, <QueryLog: QueryLog object (2585278)>, <QueryLog: QueryLog object (2585277)>, '...(remaining elements truncated)...']>> QueryLog objects older than 60 days.`

I assume that the log output should be as,
`Deleting 100 QueryLog objects older than 90 days.`
assuming count as 100, days as 90.

Is my assumption correct? if yes, can I add the fix?

Thanks,
Bhola

**Comment by chrisclark** [comment]
You are correct! Yes please open a PR for the fix (or I can just fix it myself -- just let me know). Thanks!
